
name: CLI-WEB

permissions:
  contents: write

on:
  push:
    branches:
      - "main"
      - "release-*"
      - "*"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Prepare source name: Tag or branch name"
        id: prepare_source
        run: |
          SOURCE_NAME="${GITHUB_REF#refs/*/}"
          VERSION_FILE=version.txt

          # Leer la versión actual desde el archivo (version.txt) o usar '0.0' si no existe
          if [ -f $VERSION_FILE ]; then
            CURRENT_VERSION=$(cat $VERSION_FILE)
          else
            CURRENT_VERSION="0.0"
          fi

          if [ "$SOURCE_NAME" == "main" ]; then
            # Incrementar la parte 'x' de la versión y reiniciar 'y'
            IFS='.' read -r x y <<< "$CURRENT_VERSION"
            NEW_VERSION="$((x + 1)).$y"
            echo "SOURCE_NAME=latest" >> $GITHUB_ENV
            SAVE="$((x + 1)).0"
          else 
            # Incrementar la parte 'y' de la versión
            IFS='.' read -r x y <<< "$CURRENT_VERSION"
            NEW_VERSION="$x.$((y + 1))"
            echo "SOURCE_NAME=$NEW_VERSION" >> $GITHUB_ENV
            SAVE="$NEW_VERSION"
          fi

          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "SAVE=$SAVE" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS}}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: gastonnicora/remates-vue
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          context: .
          file: ./Dockerfile 
          tags: |
            gastonnicora/remates-vue:${{ env.NEW_VERSION }}
            gastonnicora/remates-vue:${{ env.NEW_VERSION }}

      - name: Commit version.txt
        run: |
          VERSION_FILE=version.txt
          echo "${{ env.SAVE }}" > $VERSION_FILE
          git config --local user.name "github-actions"
          git config --local user.email "action@github.com"
          git add $VERSION_FILE
          git commit -m "Update version.txt to $SAVE" || echo "No changes to commit"
          git push

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} 

 
   